#!/bin/bash -e

# We always want a clean build
git clean -x -d -f

# The single carat capitalizes the first letter of the BUILD_TYPE string
cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE^} .

# Run the make in such a way that all output goes both to the console and to a
# file unique to the build type.  Seeing the output in the Jenkins console is
# handy, but we also need to analyze the output from builds of multiple types in
# the same pipeline branch independently.  It's difficult to do that when all
# the output went to the same console.
make -j 8 -B $TARGET 2>&1 | tee build.$BUILD_TYPE.out
