#!/bin/bash -e

# We always want a clean build
git clean -x -d -f

# CMAKE_BUILD_TYPE is apparently not case sensitive
cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -G "Unix Makefiles" .

# Run the make in such a way that all output goes both to the console and to a file unique to
# the build type.  Seeing the output in the Jenkins console is handy, but we also need to
# analyze the output from builds of multiple types in the same pipeline branch independently.
# It's difficult to do that when all the output went to the same console.
make -j 8 -B ${TARGET} 2>&1 | tee buildlog.${BUILD_TYPE}.txt
