#!/bin/bash -e

# All stages should change directory to here
cd $STAGE_DIR

git clean -x -d -f
../bin/run-cmake --$BUILD_TYPE .

# Run the make in such a way that all output goes both to the console and to a
# file unique to the build type.  Seeing the output in the Jenkins console is
# handy, but we also need to analyze the output from builds of multiple types in
# the same pipeline branch independently.
make -j 8 -B $TARGET 2>&1 | tee make.$BUILD_TYPE.out
