#!/bin/bash -e

make clean
scan-build ../bin/run-cmake --debug .

# Use --status-bugs to make this return 1 when issues are discovered
scan-build -o clangScanBuildReports -v -v --use-cc clang --use-analyzer=/usr/bin/clang make -j 8 -B tests
